# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeuteroPpCli < Formula
  desc "Every Deutero endpoint, plus the flow-behaviour and fielding answers that take many API calls to assemble and that no single endpoint returns."
  homepage "https://github.com/deutero-ai/deutero-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/deutero-ai/deutero-cli/releases/download/v0.1.0/deutero-pp-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "79f084844bbcc577931febd5ed78f864cab5f59775ee7f16aeb48552e01d31f8"

      define_method(:install) do
        bin.install "deutero-pp-cli"
        bin.install "deutero-pp-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deutero-ai/deutero-cli/releases/download/v0.1.0/deutero-pp-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "35667ad57e48e8bd43005249c77409ba988c8d380c9c3299ed052fdd110c9ba7"
      define_method(:install) do
        bin.install "deutero-pp-cli"
        bin.install "deutero-pp-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deutero-ai/deutero-cli/releases/download/v0.1.0/deutero-pp-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "a5e99c63845392fd0219512749a095c109fabc17ab50a443f64cf7464796d14c"
      define_method(:install) do
        bin.install "deutero-pp-cli"
        bin.install "deutero-pp-mcp"
      end
    end
  end

  test do
    system "#{bin}/deutero-pp-cli", "version"
  end
end
